### ISSUE TITLE
jquery.event.props undefined

### ISSUE THREAD

**Issue by aloiseau17** [zurb/twentytwenty#60]
Above all thank you for your plugin, very useful to present work.

I'm encountering an error with jquery.event.move using jquery 3.0.0 but not 2.2.3.
At page render I've got this error : 
`Uncaught TypeError: Cannot read property 'indexOf' of undefined` 
on `jquery.event.move.js:580`

Do you know where does it come ?

**Comment by takariendire** [comment]
same problem here

**Comment by Hintalo** [comment]
This issue is possibly related to the breaking change in jQuery version 3.0.0 that is reported [here.](https://github.com/stephband/jquery.event.move/issues/31)

See also the answer for [this Stackoverflow question](http://stackoverflow.com/questions/38682004/jquery-event-props-is-undefined) where some workaround possibilities are mentioned as well.

**Comment by raphaeleidus** [comment]
This is now corrected.
