### ISSUE TITLE
Getting Uncaught ReferenceError: $ is not defined only when the homepage gets reloaded...

### ISSUE THREAD

**Issue by bradpaulp** [zurb/twentytwenty#77]
Hello,
I hope this is the right area to address this. I have this site: [www.cumberlandkitchen.com](url) , I'm using the TwentyTwenty slider on the home page AND on another page called /before-and-after.

What's very strange, is that on the /before-and-after page, there is no issues running the TT plugin, and I have multiple instances of it runnning on that page.

On the homepage however, different story. It will load only the first time correctly, after that I am getting a "Uncaught ReferenceError: $ is not defined at..."

Any ideas?

I'm loading it on the homepage the exact same way as the other pages. Only the homepage is giving this issue.

:(

**Comment by raphaeleidus** [comment]
You have a race condition with jquery that is causing your problem
you are including jquery after the script that initialized TwentyTwenty. It works the first time because you are have a `defer` on the script but once the resource is cached it wont work correctly.
You should move you script on line 400 of your html to be below the inclusion on jQuery. Hope this helps. Sorry for the slow response
